---

#
# Install Visual Studio
#

#- when: vs == 2013
#  block:
#  # TODO: Ensure no other versions are installed
#  - name: install Visual Studio 2013
#    include_tasks: "partials/vs2013.yml"
#
#- when: vs == 2015
#  block:
#  # TODO: Ensure no other versions are installed
#  - name: install Visual Studio 2015
#    include_tasks: "partials/vs2015.yml"
#
#- when: vs == 'vcbt2015'
#  block:
#  # TODO: Ensure no other versions are installed
#  - name: install Visual C++ Build Tools 2015
#    include_tasks: "partials/vcbt2015.yml"
#
#- when: vs == 2017
#  block:
#  # TODO: Ensure no other versions are installed
#  - name: install Visual Studio 2017
#    include_tasks: "partials/vs2017.yml"


#
# Install Visual Studio 2015
#

- name: download Visual Studio Community 2015
  win_get_url:
    url: 'https://go.microsoft.com/fwlink/?LinkId=532606'
    dest: 'C:\TEMP\vs2015_community.exe'
    force: no

- name: install Visual Studio Community 2015
  win_command: 'C:\TEMP\vs2015_community.exe /Silent /NoRestart
                /InstallSelectableItems NativeLanguageSupport_Group
                /Log C:\TEMP\vs2015_install_log.txt'

- name: install WiX Toolset
  import_tasks: 'wixtoolset.yml'




#
# Install Visual C++ Build Tools 2015
#

- name: download .NET Framework
  win_get_url:
    url: 'http://go.microsoft.com/fwlink/?LinkId=671743'
    dest: 'C:\TEMP\netfw.exe'
    force: no

- name: install .NET Framework
  win_command: 'C:\TEMP\netfw.exe /q /norestart /log C:\TEMP\netfw_install_log.txt'

- name: download Visual C++ Build Tools 2015
  win_get_url:
    url: 'https://go.microsoft.com/fwlink/?LinkId=691126'
    dest: 'C:\TEMP\vcbt2015.exe'
    force: no

- name: install Visual C++ Build Tools 2015
  win_shell: 'C:\TEMP\vcbt2015.exe /Silent /NoRestart /Full /Log C:\TEMP\vsbt2015_install_log.txt'
  args:
    executable: cmd
  tags: skip

- name: install WiX Toolset
  import_tasks: 'wixtoolset.yml'



#
# Install Visual Studio 2013
#


- name: download Visual Studio Community 2013
  win_get_url:
    url: 'https://go.microsoft.com/fwlink/?LinkId=532495'
    dest: 'C:\TEMP\vs2013_community.exe'

- name: install Visual Studio Community 2013
  win_shell: 'C:\TEMP\vs2013_community.exe /Silent /NoRestart /Log C:\TEMP\vs2013_install_log.txt'
  args:
    executable: cmd

- name: install WiX Toolset
  import_tasks: 'wixtoolset.yml'


#
# Install Visual Studio 2017
#


- name: install Visual Studio Community 2017
  win_chocolatey: name=visualstudio2017community

- name: install Visual Studio Community 2017 Native Desktop Workload
  win_chocolatey: name=visualstudio2017-workload-nativedesktop

- name: install WiX Toolset
  import_tasks: 'wixtoolset.yml'

# Note: https://chocolatey.org/docs/helpers-install-chocolatey-vsix-package exists, but
# can't be used with VS2017 yet: https://github.com/chocolatey/choco/issues/1201

- name: download WiX Toolset Visual Studio Extension
  win_get_url:
    url: 'https://github.com/wixtoolset/VisualStudioExtension/releases/download/v0.9.21.62588/Votive2017.vsix'
    dest: 'C:\TEMP\Votive2017.vsix'

- name: install WiX Toolset Visual Studio Extension
  win_shell: '& "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VSIXInstaller.exe" /quiet C:\TEMP\Votive2017.vsix'
  
